### ISSUE TITLE
Some broken search

### ISSUE THREAD

**Issue by voidplayer** [hssm/anki-ignore-accents#3]
```deck:"mydeck" is:due prop:due>-30```

Not sure what exactly breaks it, but this is the typical search to limit your overdued cards

**Comment by hssm** [comment]
Are you running the latest version of the add-on? I have no issue with this query. (And the internal query is identical to the input string, after the add-on processes it, so it's not even doing anything).

**Comment by voidplayer** [comment]
Im running the latest version

Maybe is the space in the deck name? I am actually using a deck called ```deck:"my deck" is:due prop:due>-30```

I tried on a different deck without spaces and it indeed worked

Disabling the addon return results on the serach and when i enable it again, it returns 0 results

**Comment by voidplayer** [comment]
Yup, is the space. I renamed the deck to remove the space and it worked :)

**Comment by hssm** [comment]
It was handling the case where the deck term was `"deck:my deck"` and not `deck:"my deck"`. I've pushed a new version that handles this as well.
