### ISSUE TITLE
latest update 2.1.41 breaks this plugin

### ISSUE THREAD

**Issue by voidplayer** [hssm/anki-ignore-accents#4]

**Comment by itsdomme** [comment]
Yes, I confirm. A lot of results are missing in the search - also in 2.1.42.

Edit: The problem is still exists. Does anyone have a solution?

**Comment by itsdomme** [comment]
I suppose it's working again in 2.1.46, doesn't it?

**Comment by voidplayer** [comment]
latest release is 2.1.45. I had it disabled and enabled it again and it does work
